services:
    mdn_admin.form.type.role:
        class: MDN\AdminBundle\Resources\Form\Type\RoleType
        tags:
            - { name: form.type, alias: role }
            
    mdn_admin.form.type.user:
        class: MDN\AdminBundle\Resources\Form\Type\UserType
        tags:
            - { name: form.type, alias: user }