services:            
    mdn_my_sys.form.type.server:
        class: MDN\MySysBundle\Resources\Form\Type\ServerType
        tags:
            - { name: form.type, alias: server }
            
    mdn_my_sys.form.type.domain:
        class: MDN\MySysBundle\Resources\Form\Type\DomainType
        tags:
            - { name: form.type, alias: domain }